abs_dag_config:
  func_vocab:
  - ADD
  - MUL
  max_fan_in_deg: 3
  min_fan_in_deg: 1
  mod_val: 23
  num_leaf_nodes: 6
  num_nodes: 32
  verbose: false
batch_size: 64
dag_config:
  data_dir: data
  data_file_name: dag.json
  func_vocab:
  - ADD
  max_fan_in_deg: 3
  min_fan_in_deg: 1
  mod_val: 23
  num_leaf_nodes: 6
  num_nodes: 32
  verbose: false
  vocab_file_name: dag_vocab.yaml
data_dir: <data_dir>
data_file_name: <data_file_name>
ins_dag_config:
  func_vocab:
  - ADD
  - MUL
  max_fan_in_deg: 3
  min_fan_in_deg: 1
  mod_val: 23
  num_leaf_nodes: 6
  num_nodes: 32
  verbose: true
num_samples: 100000
vocab_file_name: <vocab_file_name>
vocab_size: 61
