StepLR_scheduler_config:
  gamma: 0.1
  step_size: 1000
batch_size: 64
cosine_scheduler_config:
  lr_decay_steps: 100000000.0
  min_lr: 1.0e-05
  warmup_steps: 1000
learning_rate: 0.01
lr_scheduler: cosine
max_epochs: 100
num_workers: 4
optimizer: AdamW
seed: 42
wandb_config:
  wandb_entity: scgpt-siyu
  wandb_project: composition_v1
weight_decay: 0.01
